# Principal Component Analysis with the `scikit-learn` library

Imports

In [3]:
# Imports
import numpy as np
from sklearn.decomposition import PCA

Data Preparation

In [4]:
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])

Using PCA

In [8]:
pca = PCA(n_components=1)
X_reduced = pca.fit_transform(X)
X_recoverd = pca.inverse_transform(X_reduced)

X, X_reduced, X_recoverd

(array([[-1, -1],
        [-2, -1],
        [-3, -2],
        [ 1,  1],
        [ 2,  1],
        [ 3,  2]]),
 array([[-1.38340578],
        [-2.22189802],
        [-3.6053038 ],
        [ 1.38340578],
        [ 2.22189802],
        [ 3.6053038 ]]),
 array([[-1.15997501, -0.75383654],
        [-1.86304424, -1.21074232],
        [-3.02301925, -1.96457886],
        [ 1.15997501,  0.75383654],
        [ 1.86304424,  1.21074232],
        [ 3.02301925,  1.96457886]]))